//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyshow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedSeat
    {
        public int TheatreId { get; set; }
        public int SlotId { get; set; }
        public int MovieId { get; set; }
        public string SeatNumber { get; set; }
        public int UserId { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual Slot Slot { get; set; }
        public virtual Theatre Theatre { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
