//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyshow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayOffer
    {
        public int PlayId { get; set; }
        public int OfferId { get; set; }
        public string CouponCode { get; set; }
    
        public virtual Offer Offer { get; set; }
        public virtual Play Play { get; set; }
    }
}
