//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyshow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketDetail()
        {
            this.TicketSeats = new HashSet<TicketSeat>();
        }
    
        public int TicketId { get; set; }
        public decimal Price { get; set; }
        public int MovieId { get; set; }
        public int TheatreId { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual Theatre Theatre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketSeat> TicketSeats { get; set; }
    }
}
