//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyshow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSeat
    {
        public int TicketId { get; set; }
        public string SelectedSeat { get; set; }
    
        public virtual TicketDetail TicketDetail { get; set; }
    }
}
